[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
requires-python = ">= 3.10"
name = "bostontwin"
version = "1.0.0"
description = "Boston Twin - The Boston Digital Twin for EM Simulation"
readme = "README.md"
license = {text = "Apache-2.0"}
authors = [
    { name = "Paolo Testolina", email = "p.testolina@northeastern.edu" }
]
dependencies = [
"geopandas",
"open3d",
"pycollada",
"numpy",
# "mitsuba",
"requests",
"rasterio",
"contextily",
]

[project.optional-dependencies]
sionna-rt=["sionna-rt"]

[tool.uv]
package = true