[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "sionna-rt",
    "geopandas",
    "open3d-cpu",
    "pycollada",
    "numpy",
    "mitsuba",
    "requests"
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]  # list of folders that contain the packages (["."] by default)
include = ["src"]  # package names should match these glob patterns (["*"] by default)
exclude = []  # exclude packages matching these glob patterns (empty by default)
namespaces = false  # to disable scanning PEP 420 namespaces (true by default)