[metadata]
name = bostontwin
version = 0.1
author = Paolo Testolina
author_email=p.testolina@northeastern.edu
description = BostonTwin
long_description = file: README.md
long_description_content_type = text/markdown
url = https://wineslab.github.io/boston_twin/
download_url = https://github.com/wineslab/boston_twin/
project_urls =
    Bug Tracker = https://github.com/wineslab/boston_twin/issues
classifiers = 
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
package_dir == .
packages = find_namespace:
include_package_data = True
python_requires = >=3.8

install_requires =
    numpy
    geopandas
    mitsuba
    requests
    contextily
    open3d
    jupyter
    sionna
    pycollada

[options.package_data]
* = *.csv, *.npy, *.json, *.xml, *.ply, *.geojson

[options.packages.find]
where = .
exclude =
    docs*
    dist*
    test*
    dataset*

[options.exclude_package_data]
docs* = *
dist* = *
test* = *
dataset* = *
